pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Ayrus-kira/devops-portfolio.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t devops-portfolio ./docker-project'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 80:80 devops-portfolio'
            }
        }
    }
}
